In [1]:
import numpy as np
import pickle
import torch
import os
#data = pickle.load('Dataset/English_sentences.pkl')
load = torch.load(os.path.join("Dataset", "German_sentences.pkl"))

In [2]:
len(load)

7

In [3]:
load["train_data"]

[tensor([2, 3, 4, 3]),
 tensor([ 5,  3,  6,  3,  7,  3,  8,  3,  9, 10, 11,  3, 12,  3, 11, 13, 11, 14,
         11, 15, 11,  3, 16,  3, 17,  3, 18,  3, 19,  3, 20,  3, 21,  3, 22,  3,
         23, 10, 11,  3, 24,  3, 25,  3, 26,  3, 27,  3, 28,  3, 29,  3, 30,  3,
         31,  3, 32, 10, 11,  3, 33,  3, 34,  3, 35,  3, 36,  3, 37, 15]),
 tensor([38,  3, 34,  3, 39,  3, 40, 10, 11,  3, 41,  3,  4,  3, 42,  3, 11, 43,
         44, 45, 46,  3, 11, 43, 11,  3, 47,  3, 48, 15, 11,  3, 49,  3, 50,  3,
         51,  3, 52,  3, 53,  3, 54,  3, 55,  3, 56,  3, 57,  3, 58,  3, 59, 15]),
 tensor([60,  3, 61,  3, 62,  3,  4,  3, 63,  3, 64,  3, 65,  3, 66,  3, 67,  3,
         68,  3, 69,  3, 18,  3, 70,  3, 71,  3, 72,  3, 73, 15]),
 tensor([74,  3, 75,  3, 76,  3, 34,  3, 77,  3, 11, 45, 11,  3, 78,  3, 41,  3,
         79,  3,  4,  3, 63,  3, 52,  3, 80,  3, 31,  3, 81,  3, 11, 45, 11, 10,
         11,  3, 82,  3, 83,  3,  4,  3, 84, 10, 11,  3, 85,  3, 70,  3, 71,  3,
         86,  3, 87,  3

In [4]:
load["test_data"]

[tensor([1410,    3,   34,    3,  417,    3,    7,    3, 1411,   10,   11,    3,
            7,    3,   93,    3,   70,    3,   71,    3,  374,    3,  691,    3,
           67,    3, 1412,    3, 1413,    3,  325,   15,   11,    3, 1414,    3,
           70,    3, 1415,   10,   11,    3,   71,    3, 1416,    3,   31,    3,
         1300,    3,   87,    3, 1417,    3, 1418,    3,  220,    3, 1419,    3,
         1420,    3,   31,    3, 1184,    3,   47,   10,   11,    3,  432,    3,
          109,    3,  589,    3,    4,    3, 1421,    3, 1388,    3, 1394,    3,
         1422,    3,  237,   10,   11,    3,    8,    3, 1423,    3, 1424,   15]),
 tensor([1425,    3, 1426,    3,   34,    3,  417,    3, 1427,    3,   56,    3,
         1428,    3, 1429,   10,   11,    3,    7,    3,  347,    3, 1430,    3,
          143,    3, 1431,    3,   31,    3,   56,    3, 1220,    3,  331,    3,
         1432,    3, 1433,    3, 1434,   15]),
 tensor([1435,    3, 1436,    3, 1437,    3,   70,    3, 143

In [9]:
load['vocab']

4790

In [5]:
load["vocab_reversed"]

['<start>',
 '<end>',
 'Wiederaufnahme',
 ' ',
 'der',
 'Ich',
 'erkläre',
 'die',
 'am',
 'Freitag',
 ',',
 '',
 'dem',
 '1',
 '7',
 '.',
 'Dezember',
 'unterbrochene',
 'Sitzungsperiode',
 'des',
 'Europäischen',
 'Parlaments',
 'für',
 'wiederaufgenommen',
 'wünsche',
 'Ihnen',
 'nochmals',
 'alles',
 'Gute',
 'zum',
 'Jahreswechsel',
 'und',
 'hoffe',
 'daß',
 'Sie',
 'schöne',
 'Ferien',
 'hatten',
 'Wie',
 'feststellen',
 'konnten',
 'ist',
 'gefürchtete',
 '"',
 'Millenium',
 '-',
 'Bug',
 'nicht',
 'eingetreten',
 'Doch',
 'sind',
 'Bürger',
 'einiger',
 'unserer',
 'Mitgliedstaaten',
 'Opfer',
 'von',
 'schrecklichen',
 'Naturkatastrophen',
 'geworden',
 'Im',
 'Parlament',
 'besteht',
 'Wunsch',
 'nach',
 'einer',
 'Aussprache',
 'im',
 'Verlauf',
 'dieser',
 'in',
 'den',
 'nächsten',
 'Tagen',
 'Heute',
 'möchte',
 'ich',
 'bitten',
 'das',
 'auch',
 'Kolleginnen',
 'Kollegen',
 'allen',
 'Opfern',
 'Stürme',
 'insbesondere',
 'verschiedenen',
 'Ländern',
 'Union',
 'Schwei

In [6]:
load["max_len"]

256